import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import '../../auth/providers/auth_provider.dart';
import '../models/hall_booking_model.dart';
import '../providers/hall_booking_provider.dart';

class CreateHallBookingScreen extends ConsumerStatefulWidget {
  final HallBooking? existingBooking;

  const CreateHallBookingScreen({super.key, this.existingBooking});

  @override
  ConsumerState<CreateHallBookingScreen> createState() => _CreateHallBookingScreenState();
}

class _CreateHallBookingScreenState extends ConsumerState<CreateHallBookingScreen> {
  final _formKey = GlobalKey<FormState>();
  bool _isLoading = false;
  
  DateTime? _startDate;
  DateTime? _endDate;
  String? _selectedTimeSlot;
  final _eventNameController = TextEditingController();
  final _guestCountController = TextEditingController();

  final List<String> _timeSlots = [
    'Morning (8 AM - 12 PM)',
    'Afternoon (1 PM - 5 PM)',
    'Evening (6 PM - 11 PM)',
    'Full Day'
  ];

  @override
  void initState() {
    super.initState();
    if (widget.existingBooking != null) {
      final b = widget.existingBooking!;
      _eventNameController.text = b.eventName;
      _guestCountController.text = b.guestCount.toString();
      _selectedTimeSlot = b.timeSlot;
      try {
        _startDate = DateFormat('yyyy-MM-dd').parse(b.date);
        _endDate = DateFormat('yyyy-MM-dd').parse(b.endDate);
      } catch (_) {}
    }
  }

  Future<void> _pickDate() async {
    final now = DateTime.now();
    final initialRange = (_startDate != null && _endDate != null)
        ? DateTimeRange(start: _startDate!, end: _endDate!)
        : null;

    final picked = await showDateRangePicker(
      context: context,
      initialDateRange: initialRange,
      firstDate: now,
      lastDate: now.add(const Duration(days: 365)),
      helpText: 'SELECT BOOKING DATE RANGE',
    );
    if (picked != null) {
      setState(() {
        _startDate = picked.start;
        _endDate = picked.end;
      });
    }
  }

  void _submit() async {
    if (_formKey.currentState!.validate() && _startDate != null && _endDate != null && _selectedTimeSlot != null) {
      setState(() { _isLoading = true; });
      
      try {
        final startDateStr = DateFormat('yyyy-MM-dd').format(_startDate!);
        final endDateStr = DateFormat('yyyy-MM-dd').format(_endDate!);
        
        // Check availability (exclude current booking from conflict check if it's the same date/time)
        if (widget.existingBooking == null || 
            widget.existingBooking!.date != startDateStr || 
            widget.existingBooking!.endDate != endDateStr ||
            widget.existingBooking!.timeSlot != _selectedTimeSlot) {
          final isAvailable = await ref.read(hallBookingServiceProvider).isSlotAvailable(startDateStr, endDateStr, _selectedTimeSlot!);
          if (!isAvailable) {
            setState(() { _isLoading = false; });
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('The selected date range or time slot has conflicting approved bookings.')),
              );
            }
            return;
          }
        }

        final flatId = ref.read(authProvider).flatId ?? '';
        
        if (widget.existingBooking != null) {
          final updatedBooking = HallBooking(
            id: widget.existingBooking!.id,
            flatId: flatId,
            eventName: _eventNameController.text.trim(),
            date: startDateStr,
            endDate: endDateStr,
            timeSlot: _selectedTimeSlot!,
            guestCount: int.tryParse(_guestCountController.text) ?? 0,
            status: widget.existingBooking!.status,
            createdAt: widget.existingBooking!.createdAt,
            updatedAt: DateTime.now().toIso8601String(),
          );
          await ref.read(hallBookingServiceProvider).updateBooking(updatedBooking);
        } else {
          final newBooking = HallBooking(
            id: '', // Generated by Firestore
            flatId: flatId,
            eventName: _eventNameController.text.trim(),
            date: startDateStr,
            endDate: endDateStr,
            timeSlot: _selectedTimeSlot!,
            guestCount: int.tryParse(_guestCountController.text) ?? 0,
            status: 'pending',
            createdAt: DateTime.now().toIso8601String(),
            updatedAt: DateTime.now().toIso8601String(),
          );
          await ref.read(hallBookingServiceProvider).createBooking(newBooking);
        }
        
        setState(() { _isLoading = false; });
        
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(widget.existingBooking != null ? 'Booking request updated successfully!' : 'Hall booking request submitted successfully!')),
          );
          context.pop();
        }
      } catch (e) {
        setState(() { _isLoading = false; });
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error processing request: $e')),
          );
        }
      }
    } else if (_startDate == null || _endDate == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a date range from the calendar')),
      );
    }
  }

  @override
  void dispose() {
    _eventNameController.dispose();
    _guestCountController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.existingBooking != null ? 'Edit Booking Request' : 'Book Community Hall'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Select Date',
                style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              InkWell(
                onTap: _pickDate,
                child: Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    border: Border.all(color: Theme.of(context).colorScheme.surfaceContainerHighest),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Row(
                    children: [
                      Icon(Icons.calendar_month, color: Theme.of(context).colorScheme.primary),
                      SizedBox(width: 12),
                      Text(
                        _startDate == null || _endDate == null
                            ? 'Tap to select date range'
                            : _startDate == _endDate
                                ? DateFormat('EEEE, MMM d, yyyy').format(_startDate!)
                                : '${DateFormat('EEEE, MMM d').format(_startDate!)} - ${DateFormat('EEEE, MMM d, yyyy').format(_endDate!)}',
                        style: TextStyle(
                          fontSize: 16,
                          color: _startDate == null ? Theme.of(context).colorScheme.onSurfaceVariant : Theme.of(context).colorScheme.onSurface.withValues(alpha: 0.87),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              SizedBox(height: 24),

              Text(
                'Select Time Slot',
                style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              DropdownButtonFormField<String>(
                decoration: InputDecoration(
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                  contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                ),
                hint: Text('Choose a timing dropdown'),
                value: _selectedTimeSlot,
                items: _timeSlots.map((slot) {
                  return DropdownMenuItem(value: slot, child: Text(slot));
                }).toList(),
                onChanged: (val) {
                  setState(() {
                    _selectedTimeSlot = val;
                  });
                },
                validator: (val) => val == null ? 'Please select a time slot' : null,
              ),
              SizedBox(height: 24),

              Text(
                'Event Details',
                style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              TextFormField(
                controller: _eventNameController,
                decoration: InputDecoration(
                  labelText: 'Event Name (e.g., Birthday Party)',
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                ),
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
              ),
              SizedBox(height: 16),
              TextFormField(
                controller: _guestCountController,
                keyboardType: TextInputType.number,
                decoration: InputDecoration(
                  labelText: 'Expected Number of Guests',
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                ),
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
              ),
              SizedBox(height: 32),
              
              SizedBox(
                width: double.infinity,
                height: 50,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _submit,
                  style: ElevatedButton.styleFrom(
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                  child: _isLoading 
                      ? SizedBox(width: 24, height: 24, child: CircularProgressIndicator(strokeWidth: 2))
                      : Text(widget.existingBooking != null ? 'Update Booking Request' : 'Submit Booking Request', style: TextStyle(fontSize: 16)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
