// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWUhNRMWCbsnK40tWrQI5JahvwXzmzySA',
    appId: '1:47849992844:android:f93418e120cb39fa6241a9',
    messagingSenderId: '47849992844',
    projectId: 'soc-appv1',
    storageBucket: 'soc-appv1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFqJwijcmSo-6u2IldRu0fgkXRnAJYkKg',
    appId: '1:47849992844:ios:d5bf67e19d273ccf6241a9',
    messagingSenderId: '47849992844',
    projectId: 'soc-appv1',
    storageBucket: 'soc-appv1.firebasestorage.app',
    iosBundleId: 'com.societymaintenance.societyMobileApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4rFBD8NUJAwnEDelTepGglGLEtfpMp7A',
    appId: '1:47849992844:web:43c2eeed69aff56f6241a9',
    messagingSenderId: '47849992844',
    projectId: 'soc-appv1',
    authDomain: 'soc-appv1.firebaseapp.com',
    storageBucket: 'soc-appv1.firebasestorage.app',
  );
}
